version: "3.9"

services:
  nginx:
    build: ./compose/nginx
    # volumes:
    #   - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "9113:9113" 
    depends_on:
      - web
    networks:
      - shared_network



  web:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:web
    command: /start # shell script used to run the service
    volumes:
      - .:/app
    ports:
      - 28010:8000
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - postgres
    networks:
      - shared_network


  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env/.dev-sample
    ports:
      - "5442:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network


  redis:
    image: redis:7-alpine
    networks:
      - shared_network

  celery_worker:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:worker
    command: /start-worker
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - postgres
    ports:
      - "6899:6899"  # Expose the debugger port
    networks:
      - shared_network


  celery_beat:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:beat
    command: /start-beat
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - postgres
    ports:
      - "6890:6899" 
    networks:
      - shared_network


  flower:
    image: ${DOCKERHUB_ACCOUNT}/${DOCKERHUB_REPO}:flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - postgres
    networks:
      - shared_network


  pgadmin:
    image: dpage/pgadmin4:8.9
    volumes:
      - ./compose/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5052:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    networks:
      - shared_network



networks:
  shared_network:
    external: true

volumes:
  postgres_data: