global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:4050']